# Generated by Django 5.1.1 on 2024-09-28 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bark_core', '0002_user_account_updated_at_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
