# Generated by Django 5.1.1 on 2024-09-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bark_core', '0005_remove_account_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number_hashed',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
