# Generated by Django 5.1.1 on 2024-09-30 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bark_core', '0006_alter_account_account_number_hashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='bark_core_a_user_id_05d64b_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_number_hashed',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number_encrypted',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'account_number_encrypted'], name='bark_core_a_user_id_23b0da_idx'),
        ),
    ]
