# Generated by Django 5.1.1 on 2024-09-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bark_core', '0007_remove_account_bark_core_a_user_id_05d64b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='account',
            name='bark_core_a_user_id_23b0da_idx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_number_encrypted',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
